// Correct MetaAPI URLs as provided
export const PROVISIONING_API_URL = "https://mt-provisioning-api-v1.agiliumtrade.agiliumtrade.ai"
export const CLIENT_API_URL = "https://mt-client-api-v1.london.agiliumtrade.ai"

// MetaAPI token
export const METAAPI_TOKEN =
  "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJkNTc5MTE3MzUyYjAxOTE2ZmU0MDFhMmI3MzU2MTNhNyIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6ZGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19XSwiaWdub3JlUmF0ZUxpbWl0cyI6ZmFsc2UsInRva2VuSWQiOiIyMDIxMDIxMyIsImltcGVyc29uYXRlZCI6ZmFsc2UsInJlYWxVc2VySWQiOiJkNTc5MTE3MzUyYjAxOTE2ZmU0MDFhMmI3MzU2MTNhNyIsImlhdCI6MTc0MzEyNzkxN30.koUTZVgD0PotxoIcxPDSbNCdJ2tkkcUBTwVPKoS8FxqePKn115xZwj7WuM8uehnOiTAo9eRpZWWXkRwOzRvS6tH1hjE8yb5kBmFq3gxuIZLcbqX38p2Lhie2ckmhg6-_nRo7EwM7VW6-sUBLiOI31lPy6rAmA58tfLXq6qkuwrin7Ns_iKkiT8usVFT5Z6m1EB8VlcXJl6kmYtfEk3iLEa2KebxE9FIYWaEZ1Y5Cf_vYInpfbDniM8NoJc58qdIeJz05YDTPXNqLzdyMeKS-53nDU--YZT63WLi3VpnNb-GsH5ccYTMNRgI-CyvyigDExF7rshR-RztSz_98V23-eWGW-huW9HI44P4ijLL09H1RmI7IwsChJu766x0wYcgdNi1abyDMPk_uM09EIqdXysvgNqbZYgiDJjTa_DDN0LkKC6u01NDeOycU26Zf3fFs4chB2fX_pK36pOtSG4L8VIrZRtdfb8_d0i0h7TtLGV01GZpMweHN8RExX2CSU_MJS83ca6Pby5juPWY7O0dY-ZIRhuotPVljpcsB61xpHmHmFXi0cbwROYMtozqS9BPBVdaepvgyZNmCVOVi_xLFW_cYaqfODXyr-j5jNaSePec1tDw6hoiRLPV7-z4RHlPWrJkyYyS-QA_X8BqzfB6H325mUm86fCdXBo-r1snvtBY"

// Define endpoints with the correct paths
export const ENDPOINTS = {
  PROVISIONING: {
    ACCOUNTS: `${PROVISIONING_API_URL}/users/current/accounts`,
    ACCOUNT: (id: string) => `${PROVISIONING_API_URL}/users/current/accounts/${id}`,
  },
  CLIENT: {
    ACCOUNT_INFO: (id: string) => `${CLIENT_API_URL}/users/current/accounts/${id}/account-information`,
    ACCOUNT: (id: string) => `${CLIENT_API_URL}/users/current/accounts/${id}`,
    TRADE: (id: string) => `${CLIENT_API_URL}/users/current/accounts/${id}/trade`,
    POSITIONS: (id: string) => `${CLIENT_API_URL}/users/current/accounts/${id}/positions`,
    ORDERS: (id: string) => `${CLIENT_API_URL}/users/current/accounts/${id}/orders`,
  },
}

